# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8c94be405137ec5f4a6842d6b6c36fdd95d0f5e68565d70bd27c01e121ac66cde64299eba226bc06817b48fc43cac1f68d3c30712cda53ed83f9cd07b35a92d

test:
  secret_key_base: 321ce38260269f703d4c423cc6af36ea34a59eefca822ea2a11d39c1f2315cb4b1dd762a01094a9316af728eaaf2d683397e423db0f47cd7da25d2b576cc3251

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
